### ISSUE TITLE
Add lost package / claim policy info

### ISSUE THREAD

**Issue by hsprince** [fredlf/The-Crowd-Supply-Guide#9]
Something like the following:

### What if my package is lost?

So you've already received a tracking number, but it has stalled or stopped moving. Unfortunately your package may be lost. If you are shipping internationally, please contact your local post office first, as they might be able to locate your package.

If your package appears lost, we can file an insurance claim to replace your items. USPS requires that a package must be in transit for at least 30 days before a claim can be filed. In addition, **all claims for lost packages must be submitted within 90 days of the shipment date.** Outside of this agreed claim period, we have no course of action with the courier. If you think your package may be lost, please [contact us](mailto:orders@crowdsupply.com?subject=Lost Package) with your order ID and tracking number.

**Comment by fredlf** [comment]
Added.
